### ISSUE TITLE
too few arguements in fiunction call ltoa(bp, c_bp)

### ISSUE THREAD

**Issue by tmadushan** [ePaperInnovation/pl-mcu-epd#1]
CCS is throwing this error during compiling at these lines. 

`ltoa(bp, c_bp);`
`ltoa(sn, c_sn);`

Truely the C function ltoa(..) requires 3 arguements. But why only two are passed here? 
`char *ltoa(long N, char *str, int base);`

**Comment by OlliLenz** [comment]
Hey, 
thanks for the info. The problem is due to a different library version. The library used for the creation did not require the passing. To solve the problem with too few arguments, simply pass the base as well.


`ltoa(bp, c_bp, 10);`
`ltoa(sn, c_sn, 10);`

**Comment by tmadushan** [comment]
Thanks @OlliLenz.
